export { default as Header } from "./header/Header";
export { default as Footer } from "./footer/Footer";
export { default as Card } from "./card/Card";
export { default as Loader } from "./loader/Loader";
export { default as Slider } from "./slider/Slider";
export { default as ShowOnLogin } from "./hidden links/HiddenLinks";
export { default as AdminOnlyRoute } from "./adminOnlyRoute/AdminOnlyRoute";
export { default as Navbar } from "./admin/navbar/Navbar";
export { default as Home } from "./admin/home/Home";
export { default as Orders } from "./admin/orders/Orders";
export { default as ViewProducts } from "./admin/viewProducts/ViewProducts";
export { default as AddProduct } from "./admin/addProduct/AddProduct";
export { default as Product } from "./product/Product";
